### ISSUE TITLE
Isn't `branch_protection_v3` superseded by `branch_protection` ?

### ISSUE THREAD

**Issue by anthr76** [mineiros-io/terraform-github-repository#121]
Hello,

It looks like this module prefers to use `branch_protection_v3` rather than `branch_protection` while the documentation here makes it sound like https://registry.terraform.io/providers/integrations/github/latest/docs/resources/branch_protection_v3 `branch_protection_v3` is the old resource and we should be preferring `branch_protection`

As `branch_protection` uses GraphQL and `branch_protection_v3` uses REST

**Comment by mariux** [comment]
Hi @anthr76,

yes, you are very right, it has been superseeded but so far all features implemented in the module could be done in v3 which has significant performance benefits as the graphql v4 version is very slow when big numbers of repositories and protections are maintained in a single terraform run. 

As long as there is no real downside we will stick to defaulting to v3 for the mentioned performance issues we saw when this was introduced into the provider.

We might add support for both versions in the future (as long as the provider also supports both versions) so that users of the module can choose.

Please see also our deprecation notice at https://github.com/mineiros-io/terraform-github-repository#var-branch_protections that makes this plan clear already.

I hope this answers your question. Do you have any features not supported by v3 that you would like to see?
