### ISSUE TITLE
Support for github provider >= 3.1.0

### ISSUE THREAD

**Issue by jojand** [mineiros-io/terraform-github-repository#61]
Hi, do you plan support for github provider >= 3.1.0? We would like to use vulnerability scanning of dependencies that was introduced in this provider version.

**Comment by mariux** [comment]
hi @jojand, thanks for the interest in our module.

Sadly `3.1.0` of the provider is a regression release and `4.0.0` was released shortly after to make the breaking changes clear in the semantic versioning. So the actual task here is to upgrade support to 4.x which we have on the roadmap already.

We can't give you a timeline atm as we are busy building and updating our AWS and upcoming GCP modules. 

I will increase priority in our internal roadmap to add support for 4.x provider and also implement all new features that were added since 3.x

**Comment by jojand** [comment]
Hi @mariux, thanks for your reply. We will be watching release notes.
