### ISSUE TITLE
Owner (org) not being set

### ISSUE THREAD

**Issue by RCheesley** [mineiros-io/terraform-github-repository#96]
Hi folks!

I came across your repos from this article: https://www.mineiros.io/blog/how-to-manage-your-github-organization-with-terraform which has given me a great headstart as a complete noob to Terraform. Thanks so much for the article and the resources! I have over 90 repos to manage in our open source project and I think this is going to be a very efficient way to work once I get my head around it all!

I'm stumbling upon a challenge though.

In your article you declare the organisation in the main.tf file however this doesn't seem to be working when I try to use the up-to-date example code from your repos.

I had to change a bunch of things by copying from your latest repos because I guess things have changed in the GitHub API since the article was written, so I expect maybe the way to declare the organisation has changed too.

I tried checking your repos for how to declare it with the updated templates but I can't seem to find it in any of your example files. I think that either it's set at the repository.tf or the main.tf level, so hedging my bets and making the request here for a snippet on how to get this working!

So far it's working perfectly, but creating everything in my personal account, not the org.

Thanks in advance for any help!

**Comment by soerenmartius** [comment]
Hi @RCheesley ,

Thanks for reaching out and my apologies for the outdated article. We are currently working on a new set of articles that are based on the updated modules, provider and in which we will use GitHub Actions as the CI server since we abandoned Semaphore some time ago.

In the meantime, I kindly refer to the provider docs: https://registry.terraform.io/providers/integrations/github/latest/docs#owner

You can either set the organization through the `organization` attribute in the provider block or by configuring  the organization through the `GITHUB_ORGANIZATION` environment variable.

**Comment by soerenmartius** [comment]
@RCheesley this is an example on how to configure the provider properly

```
terraform {
  required_providers {
    github = {
      source  = "integrations/github"
      version = "~> 4.0"
    }
  }
}

# Configure the GitHub Provider
provider "github" {
  organization = "my-org"
}
```

**Comment by soerenmartius** [comment]
@RCheesley please let us know if the above mentioned hints helped you to solve your issue. Many thanks!

**Comment by soerenmartius** [comment]
Hi @RCheesley, since I didn't hear back from you anymore, I am gonna close this issue for now. Please feel free to re-open it again in case I couldn't help you to resolve your issue. Thank You!
